### ISSUE TITLE
Cannot Install From PyPI

### ISSUE THREAD

**Issue by mdmedley** [josuebrunel/logged-requests#1]
Executing `pip install logged_requests`
generates the following error:
Collecting logged_requests
  Could not find a version that satisfies the requirement logged_requests (from versions: )
No matching distribution found for logged_requests

**Comment by josuebrunel** [comment]
Hi @mdmedley, 
sorry buddy, i screwed the publication process up. I have to find another name for the package. 
Don't hesitate to  fork the repo, rename the package then publish it. 
As soon as i have a spare time, i will fix it. Shouldn't take too long anyway

**Comment by josuebrunel** [comment]
@mdmedley it's fixed now [pypi](https://pypi.python.org/pypi/logged_requestsl).
Close the issue when everything is alright for you.

**Comment by mdmedley** [comment]
Installing from PyPI works beautifully now.

**Comment by josuebrunel** [comment]
thanks buddy
